server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market
    username: admin
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
integration:
  cart-service:
    url: http://localhost:8190/market-cart

