version: '3.1'

services:

  redis:
    image: bitnami/redis:6.2.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  mysql:
      image: mysql:8.0.26
      domainname: mysql
      command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=market
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=123456
      ports:
        - "3306:3306"

  flyway:
      image: flyway/flyway
      command: -url=jdbc:mysql://mysql:3306 -schemas=market -user=admin -password=123456 -connectRetries=60 migrate
      volumes:
        - ./flyway:/flyway/sql
      depends_on:
        - mysql