server:
  port: 8191
  servlet:
    context-path: /market-auth
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market
    username: admin
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
jwt:
  secret: wertyuioplkjhgfdxvbnm98765764edfgbnmk9876
  lifetime: 36000000